config/routes.rb
  SacramentMeetingProgram::Application.routes.draw do
  resources :hymns

  resources :items

  resources :people

  resources :admin

  resources :programs do
    collection do
      get 'print'
      get 'final'
    end
  end

  root to: 'programs#final'

end

app/models/hymn.rb
class Hymn < ActiveRecord::Base
  attr_accessible :hymn_number, :link, :title
end

app/controllers/hymns_controller.rb
class HymnsController < ApplicationController
  # GET /hymns
  # GET /hymns.json
  def index
    @hymns = Hymn.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @hymns }
    end
  end

  # GET /hymns/1
  # GET /hymns/1.json
  def show
    @hymn = Hymn.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @hymn }
    end
  end

  # GET /hymns/new
  # GET /hymns/new.json
  def new
    @hymn = Hymn.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @hymn }
    end
  end

  # GET /hymns/1/edit
  def edit
    @hymn = Hymn.find(params[:id])
  end

  # POST /hymns
  # POST /hymns.json
  def create
    @hymn = Hymn.new(params[:hymn])

    respond_to do |format|
      if @hymn.save
        format.html { redirect_to @hymn, notice: 'Hymn was successfully created.' }
        format.json { render json: @hymn, status: :created, location: @hymn }
      else
        format.html { render action: "new" }
        format.json { render json: @hymn.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /hymns/1
  # PUT /hymns/1.json
  def update
    @hymn = Hymn.find(params[:id])

    respond_to do |format|
      if @hymn.update_attributes(params[:hymn])
        format.html { redirect_to @hymn, notice: 'Hymn was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @hymn.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hymns/1
  # DELETE /hymns/1.json
  def destroy
    @hymn = Hymn.find(params[:id])
    @hymn.destroy

    respond_to do |format|
      format.html { redirect_to hymns_url }
      format.json { head :no_content }
    end
  end
end

app/views/hymns/_form.html.erb
<%= form_for(@hymn) do |f| %>
  <% if @hymn.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@hymn.errors.count, "error") %> prohibited this hymn from being saved:</h2>

      <ul>
      <% @hymn.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :link %><br />
    <%= f.text_field :link %>
  </div>
  <div class="field">
    <%= f.label :hymn_number %><br />
    <%= f.number_field :hymn_number %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/hymns/edit.html.erb
<h1>Editing hymn</h1>

<%= render 'form' %>

<%= link_to 'Show', @hymn %> |
<%= link_to 'Back', hymns_path %>

app/views/hymns/index.html.erb
<h1>Listing hymns</h1>

<table>
  <tr>
    <th>Link</th>
    <th>Hymn number</th>
    <th>Title</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @hymns.each do |hymn| %>
  <tr>
    <td><%= hymn.link %></td>
    <td><%= hymn.hymn_number %></td>
    <td><%= hymn.title %></td>
    <td><%= link_to 'Show', hymn %></td>
    <td><%= link_to 'Edit', edit_hymn_path(hymn) %></td>
    <td><%= link_to 'Destroy', hymn, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Hymn', new_hymn_path %>

app/views/hymns/new.html.erb
<h1>New hymn</h1>

<%= render 'form' %>

<%= link_to 'Back', hymns_path %>

app/views/hymns/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Link:</b>
  <%= @hymn.link %>
</p>

<p>
  <b>Hymn number:</b>
  <%= @hymn.hymn_number %>
</p>

<p>
  <b>Title:</b>
  <%= @hymn.title %>
</p>


<%= link_to 'Edit', edit_hymn_path(@hymn) %> |
<%= link_to 'Back', hymns_path %>