config/routes.rb
  SacramentMeetingProgram::Application.routes.draw do
  resources :hymns

  resources :items

  resources :people

  resources :admin

  resources :programs do
    collection do
      get 'print'
      get 'final'
    end
  end

  root to: 'programs#final'

end

app/models/program.rb
class Program < ActiveRecord::Base
  before_create :calc_defaults

  attr_accessible :announcements, :announcements2, :program_week, :body_html, :cover_pic_url

  def cover_pic
    cover_pic_url || "new-testament/jesus-raising-lazurus-634865"
  end

  protected

  def calc_defaults
   self.program_week = Date.today.sunday
   self.body_html = ""
   self.announcements = ""
   self.announcements2 = ""
  end

end

app/controllers/programs_controller.rb
class ProgramsController < ApplicationController
  # GET /programs
  # GET /programs.json
  def index
    @programs = Program.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @programs }
    end
  end

  # GET /programs/1
  # GET /programs/1.json
  def show
    @program = Program.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @program }
    end
  end

  # GET /programs/new
  # GET /programs/new.json
  def new
    @program = Program.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @program }
    end
  end

  # GET /programs/1/edit
  def edit
    @content_partial = "layouts/two_column_layout"
    @program = Program.find(params[:id])
    @people = Person.all
    @items = Item.all
    @hymns = Hymn.all
  end

  # POST /programs
  # POST /programs.json
  def create
    @people = Person.all
    @items = Item.all
    @hymns = Hymn.all

    @program = Program.create!(body_html: render_to_string('template', layout: false).html_safe)

    respond_to do |format|
        format.html { redirect_to @program, notice: 'Program was successfully created.' }
        format.json { render json: @program, status: :created, location: @program }
    end
  end

  def print
    @program = Program.last
    respond_to do |format|
      format.html {render :layout => false}
    end
  end

  # PUT /programs/1
  # PUT /programs/1.json
  def update
    @program = Program.find(params[:id])
    if params[:program_week]
      p = params[:program_week]
      params[:program] ||= {program_week: Date.new(p[:year].to_i, p[:month].to_i, p[:day].to_i)}
    end
    @program.update_attributes(params[:program])
    respond_to do |format|
      if @program.update_attributes(params[:program])
        #format.html { redirect_to @program, notice: 'Program was successfully updated.' }
        format.json { render json: {message: 'you did it!'} }
      else
        #format.html { render action: "edit" }
        format.json { render json: @program.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /programs/1
  # DELETE /programs/1.json
  def destroy
    @program = Program.find(params[:id])
    @program.destroy

    respond_to do |format|
      format.html { redirect_to programs_url }
      format.json { head :no_content }
    end
  end

  def final
    @program = Program.last
    respond_to do |format|
      format.html {render template: 'programs/show' }
      format.json { render json: @program }
    end
  end
end

app/views/programs/_form.html.erb
<%= form_for(@program) do |f| %>
  <% if @program.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@program.errors.count, "error") %> prohibited this program from being saved:</h2>

      <ul>
      <% @program.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :program_week %><br />
    <%= f.date_select :program_week %>
  </div>
  <div class="field">
    <%= f.label :announcements %><br />
    <%= f.text_area :announcements %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/programs/_lds_org_pics.json.erb
[
{ "src": "book-of-mormon/christ-appears-to-the-nephites-39663", "alt": ""},
{ "src": "book-of-mormon/the-liahona-39640", "alt": "The Liahona"},
{ "src": "book-of-mormon/lehi-people-arrive-promised-land-39644", "alt": "Lehi and His People Arrive in the Promised Land"},
{ "src": "book-of-mormon/enoch-praying-39648", "alt": "Enos Praying"},
{ "src": "book-of-mormon/mormon-abridging-the-plates-39649", "alt": "Mormon Abridging the Plates"},
{ "src": "book-of-mormon/alma-baptizing-people-39653", "alt": "Alma Baptizes in the Waters of Mormon"},
{ "src": "book-of-mormon/anti-nephi-lehies-bury-weapons-39657", "alt": "The Anti-Nephi-Lehies Burying Their Swords"},
{ "src": "book-of-mormon/christ-teaching-nephites-39665", "alt": "Jesus Teaching in the Western Hemisphere"},
{ "src": "book-of-mormon/christ-blesses-the-nephite-children-39667", "alt": "Jesus Healing the Nephites"},
{ "src": "book-of-mormon/brother-of-jared-seeing-finger-of-lord-39668", "alt": "The Brother of Jared Sees the Finger of the Lord"},
{ "src": "book-of-mormon/moroni-buries-plates-39672", "alt": "Moroni Hides the Plates in the Hill Cumorah"},
{ "src": "book-of-mormon/christ-calls-nephite-apostles-39677", "alt": "Christ with Three Nephite Disciples"},
{ "src": "book-of-mormon/behold-your-little-ones-149404", "alt": "Jesus Blesses the Nephite Children"},
{ "src": "book-of-mormon/christ-land-bountiful-174607", "alt": "Christ in the Land Bountiful"},
{ "src": "book-of-mormon/christ-blessing-nephite-children-451708", "alt": "Jesus Christ blessing the Nephite children"},
{ "src": "book-of-mormon/christ-and-the-nephite-children-83422", "alt": ""},
{ "src": "new-testament/shepherds-see-new-star-39535", "alt": "The Announcement of Christ’s Birth to the Shepherds"},
{ "src": "new-testament/mary-and-joseph-travel-to-bethlehem-39537", "alt": "Joseph and Mary Travel to Bethlehem"},
{ "src": "new-testament/boy-jesus-in-the-temple-39538", "alt": "Boy Jesus in the Temple"},
{ "src": "new-testament/carpenters-son-39540", "alt": "Childhood of Jesus Christ"},
{ "src": "new-testament/john-baptizes-christ-39544", "alt": "John the Baptist Baptizing Jesus"},
{ "src": "new-testament/calling-the-fishermen-39547", "alt": "Calling of the Fishermen "},
{ "src": "new-testament/christ-ordaining-the-apostles-39549", "alt": "Christ Ordaining the Apostles"},
{ "src": "new-testament/christ-teaching-the-people-39554", "alt": "Sermon on the Mount"},
{ "src": "new-testament/christ-healing-the-blind-man-39555", "alt": "Christ Healing a Blind Man"},
{ "src": "new-testament/jesus-calms-the-storm-39557", "alt": "Jesus Calms the Storm"},
{ "src": "new-testament/shepherds-see-new-star-39535", "alt": "The Announcement of Christ’s Birth to the Shepherds"},
{ "src": "new-testament/mary-and-joseph-travel-to-bethlehem-39537", "alt": "Joseph and Mary Travel to Bethlehem"},
{ "src": "new-testament/boy-jesus-in-the-temple-39538", "alt": "Boy Jesus in the Temple"},
{ "src": "new-testament/carpenters-son-39540", "alt": "Childhood of Jesus Christ"},
{ "src": "new-testament/john-baptizes-christ-39544", "alt": "John the Baptist Baptizing Jesus"},
{ "src": "new-testament/calling-the-fishermen-39547", "alt": "Calling of the Fishermen "},
{ "src": "new-testament/christ-ordaining-the-apostles-39549", "alt": "Christ Ordaining the Apostles"},
{ "src": "new-testament/christ-teaching-the-people-39554", "alt": "Sermon on the Mount"},
{ "src": "new-testament/christ-healing-the-blind-man-39555", "alt": "Christ Healing a Blind Man"},
{ "src": "new-testament/jesus-calms-the-storm-39557", "alt": "Jesus Calms the Storm"},
{ "src": "new-testament/go-ye-therefore-and-teach-all-nations-39610", "alt": "Go Ye Therefore and Teach All Nations"},
{ "src": "new-testament/the-ascension-of-jesus-39614", "alt": "The Ascension of Jesus"},
{ "src": "new-testament/jesus-at-the-door-39617", "alt": "Jesus at the Door"},
{ "src": "new-testament/the-second-coming-39618", "alt": "The Second Coming"},
{ "src": "new-testament/the-second-coming-39621", "alt": "The Second Coming"},
{ "src": "new-testament/jesus-christ-39623", "alt": "Jesus the Christ"},
{ "src": "new-testament/the-annunciation-gabriel-mary-39627", "alt": "The Annunciation: The Angel Gabriel Appears to Mary"},
{ "src": "new-testament/jesus-walking-on-water-129516", "alt": "Jesus Walking on the Water"},
{ "src": "new-testament/jesus-last-supper-82803", "alt": "The Last Supper"},
{ "src": "new-testament/stoning-of-stephen-360158", "alt": "The Stoning of Stephen"},
{ "src": "new-testament/mary-joseph-nativity-art-lds-191342", "alt": "The Road to Bethlehem"},
{ "src": "new-testament/angel-appears-to-shepherds-603730", "alt": "The Announcement of Christ’s Birth to the Shepherds"},
{ "src": "new-testament/ten-lepers-christ-healed-tissot-39577", "alt": "Christ Healing the Ten Lepers"},
{ "src": "new-testament/christ-rich-young-ruler-hofmann-1020802", "alt": "Christ and the Rich Young Ruler"},
{ "src": "new-testament/jesus-christ-feed-my-sheep-83279", "alt": "Jesus Christ instructs Apostles to &quot;Feed My Sheep&quot;"},
{ "src": "new-testament/christ-doctors-temple-art-lds-710197", "alt": "Boy Jesus in the Temple"},
{ "src": "new-testament/lost-lamb-art-lds-425852", "alt": ""},
{ "src": "new-testament/simeon-mary-joseph-greg-olsen-243715", "alt": "Simeon Reverencing the Christ Child"},
{ "src": "new-testament/jesus-healing-the-blind-bloch-634622", "alt": ""},
{ "src": "new-testament/christ-and-samaritan-woman-bloch-634623", "alt": ""},
{ "src": "new-testament/jesus-sermon-mount-634632", "alt": ""},
{ "src": "new-testament/jesus-birth-nativity-634637", "alt": ""},
{ "src": "new-testament/the-last-supper-carl-bloch-634699", "alt": ""},
{ "src": "new-testament/jesus-raising-lazurus-634865", "alt": ""},
{ "src": "new-testament/mary-with-boy-jesus-dewey-327093", "alt": "Jesus Praying with His Mother "},
{ "src": "new-testament/living-water-jesus-christ-610290", "alt": "Jesus and the Samaritan Woman"},
{ "src": "new-testament/pool-of-bethesda-carl-bloch-83121", "alt": "Christ Healing the Sick at Bethesda"}
]

app/views/programs/_pictures.html.erb
<div id="cover-image-preview">
  <ul class="ts_container">
    <% lds_org_pics.each do |pic| %>
      <li>
        <div class="micro-preview">
          <%= image_tag("http://media.ldscdn.org/images/media-library/gospel-art/#{pic[:src]}-thumbnail.jpg", alt: pic[:alt], "data-cover-pic" => pic[:src], style: "max-height:10px; max-width:10px") %>
        </div>
      </li>
    <% end %>
    <li class="ts_thumbnails">
      <div class="ts_preview_wrapper">
        <ul class="ts_preview"><!-- animate left to slide to the right thumb -->
          <% lds_org_pics.each do |pic| %>
            <li>
              <div class="mini-preview">
                <%= image_tag("http://media.ldscdn.org/images/media-library/gospel-art/#{pic[:src]}-thumbnail.jpg", alt: pic[:alt]) %>
              </div>
            </li>
          <% end %>
        </ul>
        <!-- List with thumbnails/preview items -->
      </div>
      <span></span>
    </li>
  </ul>
</div>
<div id="cover-preview">
  <%= image_tag("http://media.ldscdn.org/images/media-library/gospel-art/#{@program.cover_pic}-tablet.jpg", "data-cover-pic" => @program.cover_pic) %>
</div>

app/views/programs/edit.html.erb
<% content_for :main_section do %>
  <div class="edit">
    <p id="notice" xmlns="http://www.w3.org/1999/html"><%= notice %></p>

    <%= form_for(@program, :html => {:id => 'program_date'}, remote: true) do %>
      <%= select_date (@program.program_week), prefix: :program_week %>
    <% end %>

    <h4>Manhattan 3rd Ward</h4>
    <ul class="sortable-list connectedSortable ui-sortable program-page-layout">

      <%= @program.body_html.html_safe %>
    </ul>

    <div class="row">
      <div class="columns large-12">
        <b>Announcements / text inside program:</b>

        <div class="button small button-save">Save</div>
        <div id="announcements" class="editor program-page" contenteditable='true'>
          <%= @program.announcements.html_safe %>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="columns large-12 announcements">
        <b>Announcements / text on back of program:</b>

        <div class="button button-save">Save</div>
        <div id="announcements2" class="editor program-page" contenteditable='true'>
          <%= @program.announcements2.html_safe %>
        </div>
      </div>
    </div>
  </div>

<% end %>

<% content_for :side_section do %>
  <div class="row">
    <h4>Program Items</h4>
    <ul class="sortable-option-list connectedSortable selection-list">
      <%= render :partial => 'items/one_line_item_with_person', locals: {name: "Presiding", people: @people, extra_class: 'unique'} %>
      <%= render :partial => 'items/one_line_item_with_person', locals: {name: "Conducting", extra_class: 'unique', people: @people} %>
      <%= render :partial => 'items/hymn', locals: {name: "Opening Hymn", extra_class: 'unique'} %>
      <%= render :partial => 'items/one_line_item_with_person', locals: {name: "Invocation", extra_class: 'unique', people: @people} %>
      <%= render :partial => 'items/one_line_item', locals: {name: "Ward Business", extra_class: 'unique', people: @people} %>
      <%= render :partial => 'items/hymn', locals: {name: "Sacrament Hymn", extra_class: 'unique'} %>
      <%= render :partial => 'items/one_line_item', locals: {name: "Administration of the Sacrament", extra_class: 'unique', people: @people} %>
      <%= render :partial => 'items/one_line_item', locals: {name: "Bearing of Testimonies", extra_class: 'unique', people: @people} %>
      <%= render :partial => 'items/one_line_item_with_person', locals: {name: "Speaker", extra_class: 'multiple', people: @people} %>
      <%= render :partial => 'items/hymn', locals: {name: "Intermediate Hymn", extra_class: 'unique'} %>
      <%= render :partial => 'items/hymn', locals: {name: "Closing Hymn", extra_class: 'unique'} %>
      <%= render :partial => 'items/one_line_item_with_person', locals: {name: "Benediction", extra_class: 'unique', people: @people} %>
      <% @items.each do |item| %>
        <%= item.content %>
      <% end %>
    </ul>
  </div>

  <%= render partial: 'pictures' %>

<% end %>

app/views/programs/index.html.erb
<h1>Listing programs</h1>

<table>
  <tr>
    <th>Program week</th>
    <th>Announcements</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @programs.each do |program| %>
  <tr>
    <td><%= program.program_week %></td>
    <td><%= program.announcements %></td>
    <td><%= link_to 'Show', program %></td>
    <td><%= link_to 'Edit', edit_program_path(program) %></td>
    <td><%= link_to 'Destroy', program, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Program', new_program_path %>

app/views/programs/new.html.erb
<h1>New program</h1>

<%= render 'form' %>

<%= link_to 'Back', programs_path %>

app/views/programs/print.html.erb
<!DOCTYPE html>
<head>
  <meta charset="utf-8"/>

  <title>Print Program</title>
  <%= stylesheet_link_tag "application", media: 'all' %>
  <%= javascript_include_tag "vendor/custom.modernizr" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="row page-1">
  <div class="row">
    <div class="columns large-6 program-page">

      <%= @program.announcements2.html_safe %>
    </div>
    <div class="columns large-6">
      <div class="cover-pic">
        <%= image_tag("http://media.ldscdn.org/images/media-library/gospel-art/#{@program.cover_pic_url}-tablet.jpg") %>
        <h3>Manhattan 3rd Ward</h3>

        <h4><%= @program.program_week %></h4>
      </div>
    </div>

  </div>

</div>
<div class="row page-2 page-break">

  <div class="columns large-6 program-page-layout program-page">
    <div style="margin:20px 0;text-align: center;">
      <h3>Manhattan 3rd Ward</h3>

      <h4><%= @program.program_week %></h4>
    </div>
    <%= @program.body_html.html_safe %>
  </div>
  <div class="columns large-6 program-page">
    <%= @program.announcements.html_safe %>
  </div>
</div>
</body>

app/views/programs/show.html.erb
<div class="show-page">
  <div class="show-container">
      <div class="row">
        <div class="cover-pic">
          <%= image_tag("http://media.ldscdn.org/images/media-library/gospel-art/#{@program.cover_pic_url}-tablet.jpg") %>
        </div>
      </div>
    <div class="row section"  style="text-align: center;">

    <div class="row">
        <div class="columns small-12">
          <h4>Manhattan 3rd Ward</h4>
        </div>
      </div>
      <div class="row">
        <%= @program.program_week %>
      </div>
    </div>
    <div class="row section">
      <div class="columns small-12 program-page-layout">
        <%= @program.body_html.html_safe %>
      </div>
    </div>
    <div class="row section">
      <div class="columns small-12">
        <%= @program.announcements.html_safe %>
      </div>
    </div>
    <div class="row section">
      <div class="columns small-12">
        <%= @program.announcements2.html_safe %>
      </div>
    </div>

  </div>
</div>

app/views/programs/template.html.erb
<ul class="sortable-list connectedSortable">
  <%= render :partial => 'items/one_line_item_with_person', locals: {name: "Presiding"} %>
  <%= render :partial => 'items/one_line_item_with_person', locals: {name:  "Conducting"} %>
  <%= render :partial => 'items/one_line_item_with_person', locals: {name:  "Invocation"} %>
  <%= render :partial => 'items/one_line_item', locals: {name:  "Ward Business"} %>
  <%= render :partial => 'items/one_line_item', locals: {name:  "Administration of the Sacrament"} %>
  <%= render :partial => 'items/hymn', locals: {name:  "Closing Hymn"} %>
  <%= render :partial => 'items/one_line_item_with_person', locals: {name: "Benediction"} %>
</ul>