config/routes.rb
  SacramentMeetingProgram::Application.routes.draw do
  resources :hymns

  resources :items

  resources :people

  resources :admin

  resources :programs do
    collection do
      get 'print'
      get 'final'
    end
  end

  root to: 'programs#final'

end

app/models/item.rb
class Item < ActiveRecord::Base
  attr_accessible :name
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  # GET /items
  # GET /items.json
  def index
    @items = Item.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @items }
    end
  end

  # GET /items/1
  # GET /items/1.json
  def show
    @item = Item.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @item }
    end
  end

  # GET /items/new
  # GET /items/new.json
  def new
    @item = Item.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @item }
    end
  end

  # GET /items/1/edit
  def edit
    @item = Item.find(params[:id])
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(params[:item])

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render json: @item, status: :created, location: @item }
      else
        format.html { render action: "new" }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /items/1
  # PUT /items/1.json
  def update
    @item = Item.find(params[:id])

    respond_to do |format|
      if @item.update_attributes(params[:item])
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item = Item.find(params[:id])
    @item.destroy

    respond_to do |format|
      format.html { redirect_to items_url }
      format.json { head :no_content }
    end
  end
end

app/views/items/_form.html.erb
<%= form_for(@item) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/items/_hymn.html.erb
<li class="ui-state-default <%= extra_class %>" data-item-name="<%= name %>">
  <div class="one-line line droppable">
    <div class="throw-in-trash"><i class="icon-trash"></i></div>
    <div class="item-with-elipses"><%= name %></div>
    <div class="choose-item">
      <select class="chzn-select">
        <option>Pick a Hymn</option>
        <% @hymns.each do |hymn| %>
          <option value="<%= hymn.hymn_number %>" link="<%= hymn.link %>"><%= hymn.title %></option>
        <% end %>
      </select>
    </div>
    <div class="hymn modified-item">
      <a>
        <div class="hymn-number modified-name"></div>
        <div class="hymn-name modified-value">Hymn #</div>
      </a>
    </div>
  </div>
</li>

app/views/items/_one_line_item.html.erb
<li class="ui-state-default <%= extra_class %>" data-item-name="<%= name %>">
  <div class="one-line  line droppable">
    <div class="throw-in-trash"><i class="icon-trash"></i></div>
    <div class="item-without-person"><%= name %></div>
  </div>
</li>

app/views/items/_one_line_item_with_person.html.erb
<li class="ui-state-default <%= extra_class %>" data-item-name="<%= name %>">
  <div class="one-line line droppable">
    <div class="throw-in-trash"><i class="icon-trash"></i></div>
    <div class="item-with-elipses"><%= name %></div>
    <div class="choose-item">
      <select class="chzn-select">
        <option>Pick a Person</option>
        <% @people.each do |person| %>
          <option value="<%= person.id %>" link="<%= person_path(person) %>"><%= person.full_name %></option>
        <% end %>
      </select>
    </div>
    <div class="person modified-item">
      <a>
        <div class="hymn-number modified-name"></div>
      </a>
    </div>
  </div>
</li>

app/views/items/edit.html.erb
<% content_for :main_section do %>

  <h1>Editing item</h1>

  <%= render 'form' %>

  <%= link_to 'Show', @item %> |
  <%= link_to 'Back', items_path %>

<% end %>

app/views/items/index.html.erb
<% content_for :main_section do %>

<h1>Listing items</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @items.each do |item| %>
  <tr>
    <td><%= item.name %></td>
    <td><%= link_to 'Show', item %></td>
    <td><%= link_to 'Edit', edit_item_path(item) %></td>
    <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Item', new_item_path %>

<% end %>

app/views/items/new.html.erb
<% content_for :main_section do %>

<h1>New item</h1>

<%= render 'form' %>

<%= link_to 'Back', items_path %>
                                  <% end %>

app/views/items/show.html.erb
<% content_for :main_section do %>
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @item.name %>
</p>


<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>
<% end %>